### ISSUE TITLE
how do you start these apps? 

### ISSUE THREAD

**Issue by deadlyicon** [zcbenz/nw-sample-apps#13]
Can someone add that to the README?

**Comment by MartinThoma** [comment]
I needed to fix `nw` to get this work: `cat nw | sed s/libudev.so.0/libudev.so.1/ > fixed_nw`

**Comment by Paxa** [comment]
:+1: Would be nice to have it in README

**Comment by Paxa** [comment]
Added about `libudev.so.1` to https://github.com/nwjs/nw.js/wiki/How-to-run-apps
