### ISSUE TITLE
http source in script tag is not working

### ISSUE THREAD

**Issue by sasivarunan** [zcbenz/nw-sample-apps#18]
I'm trying `<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>` in one of my html but when i run it in nodewebkit im gettting below error
Failed to load resource: net:: ERR_FILE_NOT_FOUND
  file://code.jquery.com/jquery-1.9.1.min.js

Is there a way i can initialise a js file without creating a local dir like js/ and then put them in?

**Comment by Paxa** [comment]
Can you confirm with recent version of NW.js please?
Working well for me
