### ISSUE TITLE
address_bar and folder_view

### ISSUE THREAD

**Issue by timotius02** [zcbenz/nw-sample-apps#27]
I was wondering where you got the address bar and folder_view packages that you are requiring from the main.js file in the file-explorer sample. I can't seem to find where it comes from or whether or not they're a part of nw

**Comment by Paxa** [comment]
Author of that code put extra javascript files in `node_modules`
https://github.com/zcbenz/nw-sample-apps/tree/master/file-explorer/node_modules

It's not npm packages, just some js files in that folder
