### ISSUE TITLE
Frameless + Maximize / Minimize does not keep the current route.

### ISSUE THREAD

**Issue by gbraga** [zcbenz/nw-sample-apps#29]
I'm using AngularJS v1.3.15 and NW v0.12.1 with Windows 7 SP1 64 Bits.
My application (Web API) have a problem with window operations. When I called win.maximize() or anyone, the route change to Index.

I think that "var win = nw.Window.get();" see the index as your current window, because the window.location.path refers to index.

However, if I keep frame = true in my package.json, the frame buttons work perfectly.
The behavior of object window is different of nw than native frame.

**Comment by Paxa** [comment]
It seems like it's nw.js problem.

Can you provide some example that causes that problem?

I add minimize/maximize buttons for frameless-window example https://github.com/zcbenz/nw-sample-apps/commit/1bf6b9f621d4429dd4da0ddfbf3a6fb05596cc64
Does that problem appear too? Sorry, I don't have windows computer near me to check

**Comment by gbraga** [comment]
Sorry, I discovered the problem.
I remade my solution to be equal the examplo that I found (http://nodehead.com/node-webkit-custom-window-controls-26/).

In this example he uses <a href='#'></a>... This is the problem, but with one page (case of example) work perfectly.
I will close the issue.
Thanks!
