### ISSUE TITLE
please add unmaximized 

### ISSUE THREAD

**Issue by guri073** [zcbenz/nw-sample-apps#34]
please give me code of unmaximized .
document.querySelector('#maximize-window-button').onclick = function () {
    gui.Window.get().maximize();
  };

**Comment by sapioit** [comment]
I will try to push a fix for that... and to leave the maximized state, you have to use gui.Window.get().unmaximize();
https://github.com/nwjs/nw.js/wiki/window

**Comment by sapioit** [comment]
Yeah, done, now we need the pull request to be accepted...
https://github.com/zcbenz/nw-sample-apps/pull/36

**Comment by sapioit** [comment]
Solved.

**Comment by guri073** [comment]
Thx
