### ISSUE TITLE
Feature request: Listen Notifications from 3rdParty apps on MacOS

### ISSUE THREAD

**Issue by loretoparisi** [zcbenz/nw-sample-apps#35]
On MacOS, installed user apps can send notifications, that can read by Cocoa like using ```NSDistributedNotificationCenter``` so something like

```objective-c
NSDistributedNotificationCenter *center = [NSDistributedNotificationCenter defaultCenter];
[center addObserver:self selector:@selector(allNotifications:) name:nil object:nil];
```

Is possible to build an API to listen for notifications to be added to the Notifications API: https://github.com/nwjs/nw.js/wiki/Notification

**Comment by Paxa** [comment]
I think you should post in https://github.com/nwjs/nw.js/issues instead
I'm not developer of nw.js itself

**Comment by loretoparisi** [comment]
Done thank you for the suggestion.
